# path to the task data directory
data_dir: null

# either provide a path to a plaintext file describing the task
desc_file: null
# or provide the task goal (and optionally evaluation information) as arguments
goal: null
eval: null

log_dir: logs
workspace_dir: workspaces

# whether to unzip any archives in the data directory
preprocess_data: True
# whether to copy the data to the workspace directory (otherwise it will be symlinked)
# copying is recommended to prevent the agent from accidentally modifying the original data
copy_data: True

exp_name: null # a random experiment name will be generated if not provided

# settings for code execution
exec:
  timeout: 3600
  agent_file_name: runfile.py
  format_tb_ipython: False

generate_report: True
# LLM settings for final report from journal
report:
  model: gpt-4o-mini
  temp: 1.0

# agent hyperparams
agent:
  # how many improvement iterations to run
  steps: 10 #2000
  # whether to instruct the agent to use CV (set to 1 to disable)
  k_fold_validation: 1
  # whether to instruct the agent to generate a prediction function
  expose_prediction: False
  # whether to provide the agent with a preview of the data
  data_preview: True


  # LLM settings for coding
  code:
    model: "N/A"
    temp: 0.5

  # LLM settings for evaluating program output / tracebacks
  feedback:
    model: "N/A"
    temp: 0.5

  # hyperparameters for the tree search
  search:
    max_debug_depth: 20
    debug_prob: 1
    num_drafts: 10
