name: backdoor-trigger-recovery
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.15
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - accelerate==0.31.0
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.7.0
    - async-timeout==4.0.3
    - attrs==23.2.0
    - certifi==2024.6.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - datasets==2.20.0
    - deepspeed==0.14.4
    - dill==0.3.8
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - docstring-parser==0.16
    - eval-type-backport==0.2.0
    - exceptiongroup==1.2.2
    - fastchat==0.1.0
    - filelock==3.15.4
    - frozenlist==1.4.1
    - fsspec==2024.5.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - h11==0.14.0
    - hjson==3.1.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.23.4
    - idna==3.7
    - iniconfig==2.0.0
    - jinja2==3.1.4
    - jiter==0.8.2
    - joblib==1.4.2
    - lxml==5.2.2
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.5
    - multiprocess==0.70.16
    - networkx==3.2.1
    - ninja==1.11.1.1
    - nltk==3.8.1
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.555.43
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.40
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - openai==1.58.1
    - packaging==24.1
    - pandas==2.2.2
    - peft==0.11.1
    - platformdirs==4.2.2
    - pluggy==1.5.0
    - protobuf==5.27.2
    - psutil==6.0.0
    - py-cpuinfo==9.0.0
    - pyarrow==16.1.0
    - pyarrow-hotfix==0.6
    - pydantic==2.7.4
    - pydantic-core==2.18.4
    - pygments==2.18.0
    - pytest==8.3.4
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.1
    - regex==2024.5.15
    - requests==2.32.3
    - rich==13.7.1
    - safetensors==0.4.3
    - sentencepiece==0.2.0
    - sentry-sdk==2.6.0
    - setproctitle==1.3.3
    - shtab==1.7.1
    - six==1.16.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - sympy==1.12.1
    - tokenizers==0.15.2
    - tomli==2.2.1
    - torch==2.3.1
    - tqdm==4.66.4
    - transformers==4.37.2
    - triton==2.3.1
    - trl==0.9.4
    - typing-extensions==4.12.2
    - tyro==0.8.5
    - tzdata==2024.1
    - urllib3==2.2.2
    - wandb==0.17.3
    - xxhash==3.4.1
    - yarl==1.9.4
